server:
  port: 9000
az:
  rack: rack1
  zone: zone1

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
logging:
  file:
    name: ${logging.file.path}/dataServer-${server.port}.log
    path: log